apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deployment # executable id, must be unique across all your workflows (YAML files), please modify this to any value (e.g. code-pipeline-12345) if you are not the only user of your SAP AI Core instance.
  annotations:
    scenarios.ai.sap.com/description: "EvenOrOdd"
    scenarios.ai.sap.com/name: "EvenOddIdentifier"
    executables.ai.sap.com/description: "ToFindGivenNumberEvenOrOdd"
    executables.ai.sap.com/name: "EvenOrOdd" 
  labels:
    scenarios.ai.sap.com/id: "learning-code"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: credstutorialrepo # your docker registry secret
  entrypoint: mycodeblock2
  templates: 

  - name: mycodeblock2
    container:
      image: docker.io/shirke0706/even_odd:01 # Your docker image name 
      command: ["/bin/sh", "-c"]
      args: 
        - "python /app/src/main.py" 
