apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: evenoddexecutableid # Executable ID, must be unique
  annotations:
    scenarios.ai.sap.com/description: "EVENorODD"
    scenarios.ai.sap.com/name: "findEvenOrOdd"
    executables.ai.sap.com/description: "evenOrOddIdentify"
    executables.ai.sap.com/name: "evenOrOddApp"
  labels:
    scenarios.ai.sap.com/id: "learning-code"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: credstutorialrepo # Your Docker registry secret
  entrypoint: mycodeblock1
  templates: 
  - name: mycodeblock1
    container:
      image: docker.io/shirke0706/even_odd:02 # Your Docker image name  
      command: ["/bin/sh", "-c"]
      args: 
        - "python /app/src/main.py"
